project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Open Science Tools"
  description: "As the expectations of researchers increase, publishing reproducible
      scientific articles becomes essential. However, choosing tools for these
      tasks can be difficult. This course aims to guide researchers through
      these challenges by introducing a workflow that utilizes Git, GitHub,
      and the Quarto scientific and technical publishing system for collaborative
      scientific writing."
  site-url: "https://larnsce.github.io/wash-canada/"

  repo-url: https://github.com/larnsce/wash-canada
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Global Health Engineering, ETH Zurich"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: ""
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/larnsce/wash-canada
        text: "GitHub Repository"
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Course Overview
      - href: slides/hello-quarto-openwashdata.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: source
